name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Set PyPI Version
        uses: PowerGridModel/pgm-version-bump@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set version
        id: set_version
        run: |
          cp PYPI_VERSION VERSION
          cat VERSION
          echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: get run id of build workflow
        id: get_run_id
        uses: TonyXiang8787/get-run-id@main
        with:
          workflow_name: "CI"

      - name: Display run ID
        run: |
          echo "Found run ID: ${{ steps.get_run_id.outputs.run_id }}"
      
      - name: Download artifact from found run
        uses: actions/download-artifact@v4
        with:
          name: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          path: dist

      - name: Download version from found run
        uses: actions/download-artifact@v4
        with:
          name: version
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          path: old_version

      - name: set old version
        id: set_old_version
        run: |
          cat old_version/VERSION
          echo "old_version=$(cat old_version/VERSION)" >> $GITHUB_OUTPUT
      
      - name: display files, and repackage with new version
        run: |
          ls -al dist/
          ./ci-tool/patch_version.sh dist/ ${{ steps.set_old_version.outputs.old_version }} ${{ steps.set_version.outputs.version }}
          ls -al dist/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./dist/*
          tag_name: v${{ steps.set_version.outputs.version }}
          prerelease: ${{ github.ref != 'refs/heads/main'}}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
